apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-provisioner
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    helm:
      parameters:
      - name: nfs.path
        value: /mnt/IT-Academy/nfs-data/sa2-25-23/Ivanov/
      - name: nfs.server
        value: 192.168.37.105
      - name: serviceAccount.name
        value: nfs
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
  syncPolicy:
    automated: {}
